name: 'Github branch name action'
description: 'Run action to get the current branch name within Github Actions.'
author: 'Makram Jandar'
# based on https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions

runs:
  using: "composite"
  steps:
    
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
